server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5433/jira_users_db
spring.datasource.username=jira_user
spring.datasource.password=secret_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
jwt.secret.key=my_super_secret_and_incredibly_long_key_for_jira_clone_security_2026